---
apiVersion: appmanifest.mgconsulting.io/v1alpha1
name: static-site
services:
  web:
    source:
      repository: https://github.com/example/static-site.git
      build:
        context: .
        dockerfile: Dockerfile
    httpPort: 8080
stages:
  prod:
    target:
      host: edge-1
    services:
      web:
        revision: 81977d4f381dbd843d678d1daa06c78562e18466
        exposure: public
        hostname: static-site.example.com
        environment:
          NGINX_PORT:
            value: "8080"
  preview:
    target:
      host: edge-2
    services:
      web:
        revision: 81977d4f381dbd843d678d1daa06c78562e18466
        exposure: tailnet
        hostname: preview.static-site.example.com
