---
apiVersion: appmanifest.mgconsulting.io/v1alpha1
name: whoami
services:
  web:
    source:
      repository: https://github.com/traefik/whoami.git
    httpPort: 80
stages:
  dev:
    target:
      host: edge-1
    services:
      web:
        revision: b49779da6892cf6838b3452d436136a63539958d
        exposure: tailnet
        hostname: whoami.dev.example.com
        environment:
          WHOAMI_NAME:
            value: whoami-dev
