---
name: CI

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: Novirmor/cvp-cicd/.github/workflows/lint.yml@841fab16fcdd432f0e1e8980a41be557d8d9849a # main
    with:
      cache-paths: |
        ~/.local/share/mise
        ~/.cache/pre-commit
      cache-key-files: |
        mise.toml
        .pre-commit-config.yaml
        go.sum
    permissions:
      contents: read

  test:
    uses: Novirmor/cvp-cicd/.github/workflows/test.yml@841fab16fcdd432f0e1e8980a41be557d8d9849a # main
    with:
      cache-paths: |
        ~/.local/share/mise
        ~/.cache/pre-commit
        ~/.cache/go-build
      cache-key-files: |
        mise.toml
        go.sum
    permissions:
      contents: read

  security:
    uses: Novirmor/cvp-cicd/.github/workflows/security.yml@841fab16fcdd432f0e1e8980a41be557d8d9849a # main
    permissions:
      contents: read
